# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    DockerFile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/22 08:50:03 by marvin            #+#    #+#              #
#    Updated: 2024/10/22 08:50:03 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3.19

COPY 	tools/ .

RUN 	apk add --no-cache gettext && \
	 	envsubst < /tools/nginx_template.conf > /tools/nginx.conf
