# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    DockerFile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/22 08:50:03 by marvin            #+#    #+#              #
#    Updated: 2024/10/22 08:50:03 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM alpine:3.19

COPY 	tools/ .
COPY 	${DOCKER_CONFIG_FILE} .

RUN 	apk add --no-cache gettext && \
		envsubst $(cat ${DOCKER_CONFIG_FILE} | awk '{print $1}' | cut -d '=' -f1 | sed 's/^/$/' | paste -sd, - | sed "s/^/'/" | sed "s/$/'/") \
		< tools/nginx_template.conf > nginx.conf
