# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: marvin <marvin@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/22 08:50:19 by marvin            #+#    #+#              #
#    Updated: 2024/10/22 08:50:19 by marvin           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

x-common-config: &config
  env_file: config.env
  restart: always

services:
  nginx:
    <<: *config
    container_name: nginx_container
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        DOCKER_CONFIG_FILE: ${DOCKER_CONFIG_FILE}
    image: nginx_image
    ports:
      - "${PORT_FORWARD_TLS_HOST_TO_NGINX}:${PORT_LISTEN_TLS_NGINX}"
    networks:
      - inception_network



  mariadb:
    <<: *config
    container_name: mariadb_container
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DOCKER_CONFIG_FILE: ${DOCKER_CONFIG_FILE}      
    image: mariadb_image
    environment:
      MYSQL_USER_FILE: /run/secrets/db_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password

    expose:
      - ${PORT_LISTEN_MARIADB}
    networks:
      - inception_network
    secrets:
      - db_user
      - db_password
      - db_root_password


  wordpress:
    <<: *config
    container_name: wordpress_container
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DOCKER_CONFIG_FILE: ${DOCKER_CONFIG_FILE}
    image: wordpress_image
    expose: 
      - ${PORT_LISTEN_WORDPRESS}
    networks:
      - inception_network

      
networks:
  inception_network:
    driver: bridge


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/db_user.txt

volumes:
  wordpress_data:


  mariadb_data:
