#! /bin/bash

MYSQL_DB_NAME=$(cat "$MYSQL_DB_NAME_FILE")

if ! [ -d "$MYSQL_DB_NAME" ];
then
	service mariadb start


	MYSQL_USER=$(cat "$MYSQL_USER_FILE")
	MYSQL_PASSWORD=$(cat "$MYSQL_PASSWORD_FILE")
	MYSQL_ROOT_PASSWORD=$(cat "$MYSQL_ROOT_PASSWORD_FILE")

	mariadb -u root -e "
    CREATE DATABASE IF NOT EXISTS $MYSQL_DB_NAME;
    CREATE USER IF NOT EXISTS '$MYSQL_USER'@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
    GRANT ALL PRIVILEGES ON $MYSQL_DB_NAME.* TO '$MYSQL_USER'@'%';
    ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
    FLUSH PRIVILEGES;
    SHUTDOWN;"
fi

exec mysqld_safe --bind-address=0.0.0.0 --port=${PORT_LISTEN_DATABASE}
